# Generated by Django 5.2.10 on 2026-01-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this alert (used for deduplication).",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="Source system that generated this alert (e.g., 'alertmanager', 'grafana').",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(help_text="Name/title of the alert.", max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("firing", "Firing"), ("resolved", "Resolved")],
                        db_index=True,
                        default="firing",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Detailed description of the alert."
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Key-value labels associated with this alert.",
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional annotations (e.g., runbook URL, summary).",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original raw payload from the source system.",
                    ),
                ),
                ("started_at", models.DateTimeField(help_text="When the alert started firing.")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the alert was resolved (null if still firing).",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When we received this alert."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        help_text="Event type (e.g., 'created', 'resolved', 'escalated').",
                        max_length=50,
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=20)),
                ("new_status", models.CharField(blank=True, default="", max_length=20)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Alert histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Title of the incident.", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of the incident."
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Summary of what happened and resolution steps.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata for the incident."
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"], name="alerts_inci_status_682cab_idx"
                    ),
                    models.Index(fields=["created_at"], name="alerts_inci_created_5cde7d_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                help_text="Incident this alert is associated with.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="alerts.incident",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["source", "fingerprint"], name="alerts_aler_source_d6160f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["status", "severity"], name="alerts_aler_status_58cd09_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["started_at"], name="alerts_aler_started_0e1af6_idx"),
        ),
    ]
