# Generated by Django 5.2.10 on 2026-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["-received_at"], name="alerts_aler_receive_ee4265_idx"),
        ),
    ]
