# Generated by Django 5.2.16 on 2026-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_add_received_at_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("instance_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("last_source", models.CharField(blank=True, default="", max_length=64)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(fields=["-last_seen"], name="alerts_node_last_se_e8353f_idx")
                ],
            },
        ),
    ]
