# Generated by Django 5.2.16 on 2026-08-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_node"),
        ("orchestration", "0003_pipelinedefinition_channels_pipelinedefinition_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="orchestration.pipelinedefinition",
            ),
        ),
    ]
