# Generated by Django 5.2.16 on 2026-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_incident_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="trace_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Correlation ID of the pipeline run that produced this alert.",
                max_length=64,
            ),
        ),
    ]
