# Generated by Django 5.2.16 on 2026-08-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_alert_trace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent this alert came from (resolved from the instance_id label).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="alerts.node",
            ),
        ),
    ]
