# Generated by Django 5.2.16 on 2026-08-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0006_alert_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-checker hub-side policy, keyed by checker name, e.g. {"cpu": {"warning_threshold": 99, "critical_threshold": 99}}. Used to re-evaluate alert severity per node.',
            ),
        ),
    ]
