# Generated by Django 5.2.16 on 2026-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0007_node_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_self",
            field=models.BooleanField(
                default=False,
                help_text="True for the Node representing this hub itself (self-node).",
            ),
        ),
    ]
