# Generated by Django 5.2.16 on 2026-08-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0008_node_is_self"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="is_self",
        ),
    ]
