# Generated by Django 5.2.16 on 2026-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0009_remove_node_is_self"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="context_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stable digest of the situation this alert describes, used to decide whether a re-push is materially new. Empty means severity and status alone decide. See apps.alerts.context_keys.",
                max_length=255,
            ),
        ),
    ]
