build:
  nodes:
    analysis:
      environment:
        python: 3.10.0
      dependencies:
        before:
          - pip install uv
      project_setup:
        override:
          - uv sync --all-extras --dev
          - cp .env.test .env
          - echo "DJANGO_SECRET_KEY=$(python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')" >> .env
      tests:
        override:
          - py-scrutinizer-run

checks:
  python:
    code_rating: true
    duplicate_code: true

filter:
  excluded_paths:
    - "*/migrations/*"
    - "*/__pycache__/*"
    - ".venv/*"
    - "venv/*"
    - "docs/*"
    - "bin/*"
    - "tests/*"
