build:
  environment:
    python: "3.10"
    variables:
      DJANGO_SETTINGS_MODULE: "config.settings"
      DJANGO_SECRET_KEY: "scrutinizer-test-key-not-for-production"
      PYTHONPATH: "."

  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run

    tests:
      dependencies:
        before:
          - curl -LsSf https://astral.sh/uv/install.sh | sh
          - source $HOME/.local/bin/env || export PATH="$HOME/.local/bin:$PATH"

      project_setup:
        override:
          - uv sync --all-extras

      tests:
        override:
          - command: 'uv run pytest --cov=apps --cov=config --cov-report=xml:coverage.xml --cov-report=term-missing -v'
            coverage:
              file: 'coverage.xml'
              format: 'py-cc'

filter:
  excluded_paths:
    - "*/migrations/*"
    - "*/__pycache__/*"
    - ".venv/*"
    - "venv/*"
    - "docs/*"
    - "bin/*"

tools:
  external_code_coverage:
    timeout: 600
