# Generated by Django 5.2.10 on 2026-01-10 12:56

import _socket
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "checker_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the checker that was run (e.g., 'cpu', 'memory', 'disk').",
                        max_length=100,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        db_index=True,
                        default=_socket.gethostname,
                        help_text="Hostname where the check was executed.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        help_text="Result status of the check.",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Human-readable result message.")),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Measured values (e.g., {'cpu_percent': 45.2}).",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the check failed to execute.",
                    ),
                ),
                (
                    "warning_threshold",
                    models.FloatField(
                        blank=True, help_text="Warning threshold used for this check.", null=True
                    ),
                ),
                (
                    "critical_threshold",
                    models.FloatField(
                        blank=True, help_text="Critical threshold used for this check.", null=True
                    ),
                ),
                (
                    "duration_ms",
                    models.FloatField(
                        default=0.0, help_text="Duration of check execution in milliseconds."
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When the check was executed."
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Correlation ID for pipeline tracing.",
                        max_length=64,
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        help_text="Alert created from this check (if status was warning/critical).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_runs",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check Run",
                "verbose_name_plural": "Check Runs",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["checker_name", "hostname"], name="checkers_ch_checker_0b14d4_idx"
                    ),
                    models.Index(
                        fields=["status", "executed_at"], name="checkers_ch_status_4ac026_idx"
                    ),
                    models.Index(
                        fields=["checker_name", "status"], name="checkers_ch_checker_3fe825_idx"
                    ),
                ],
            },
        ),
    ]
