# Generated by Django 5.2.16 on 2026-08-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreflightRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("instance_id", models.CharField(blank=True, default="", max_length=255)),
                ("passed", models.PositiveIntegerField(default=0)),
                ("warnings", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                ("overall_status", models.CharField(default="ok", max_length=10)),
                ("triggered_by", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreflightCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("message", models.TextField(blank=True, default="")),
                ("hint", models.TextField(blank=True, default="")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="checkers.preflightrun",
                    ),
                ),
            ],
        ),
    ]
