# Generated by Django 5.2.14 on 2026-05-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config_app", "0003_apikey_owner_instance_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("hub_url", models.URLField()),
                (
                    "streams",
                    models.CharField(
                        default="events,heartbeats",
                        help_text="Comma-separated list of streams to push (e.g. 'events,heartbeats').",
                        max_length=128,
                    ),
                ),
                (
                    "forward_received",
                    models.BooleanField(
                        default=False,
                        help_text="When true, this destination also re-pushes records this host received from other agents (subject to loop-prevention via the record's `path` field). Default false: most nodes push only their own locally-generated logs.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_batch_bytes", models.PositiveIntegerField(default=10485760)),
                ("last_push_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_push_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "ok", "fail:401", "fail:5xx".',
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cluster_destinations",
                        to="config_app.apikey",
                    ),
                ),
            ],
        ),
    ]
