# Generated by Django 5.2.10 on 2026-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(db_index=True, editable=False, max_length=40, unique=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable label for this key", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allowed_endpoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of path prefixes this key can access. Empty = all.",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "config_api_key",
            },
        ),
    ]
