# Generated by Django 5.2.10 on 2026-03-22 13:33

import hashlib

from django.db import migrations, models


def hash_existing_keys(apps, schema_editor):
    """Hash all existing plaintext API keys in place and set their prefix."""
    APIKey = apps.get_model("config_app", "APIKey")
    for api_key in APIKey.objects.all():
        raw_key = api_key.key
        # Skip keys that are already 64 chars — they've been hashed (e.g. partial
        # rollback + re-apply scenario). SHA-256 digests are exactly 64 hex chars;
        # raw tokens generated by secrets.token_hex(20) are always 40 chars.
        if len(raw_key) == 64:
            continue
        if len(raw_key) < 8:
            raise ValueError(
                f"APIKey pk={api_key.pk} has an unexpectedly short key ({len(raw_key)} chars). "
                "Manual intervention required before migrating."
            )
        api_key.prefix = raw_key[:8]
        api_key.key = hashlib.sha256(raw_key.encode()).hexdigest()
        api_key.save(update_fields=["prefix", "key"])


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(default='', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        # Reverse is noop: SHA-256 hashing is one-way; raw keys cannot be recovered.
        migrations.RunPython(hash_existing_keys, migrations.RunPython.noop),
    ]
