# Generated by Django 5.2.14 on 2026-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_app", "0002_hashed_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="owner_instance_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Instance ID of the host this key was issued to. Used by cluster log forwarding's loop-prevention check. Defaults to `name` when blank.",
                max_length=64,
            ),
        ),
    ]
