"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from config.env import load_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load dotenv files early so os.environ is ready for settings below.
load_env(BASE_DIR)

# Add the 'apps' directory to sys.path
sys.path.insert(0, str(BASE_DIR / "apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Always require DJANGO_SECRET_KEY to be provided via environment/.env.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY environment variable is not set. " "Set it in your shell or .env file."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") in {"1", "true", "True", "yes", "on"}

_allowed_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS: list[str] = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.alerts.apps.AlertsConfig",
    "apps.checkers.apps.CheckersConfig",
    "apps.intelligence.apps.IntelligenceConfig",
    "apps.notify.apps.NotifyConfig",
    "apps.orchestration.apps.OrchestrationConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Celery (Queue Manager / Orchestration)
# ---------------------------------------------------------------------------
# Broker/result backend are intentionally configurable via env vars.
# Default broker uses Redis for local dev, but the *result backend* defaults to
# an in-memory backend to avoid repeated reconnect attempts when Redis isn't running.

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")

# Prefer explicit result backend configuration; fall back to a safe in-memory backend.
# If you want to use Redis for results, set:
#   CELERY_RESULT_BACKEND=redis://localhost:6379/0
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "cache+memory://")

# Keep payloads JSON-serializable so stages can pass plain dict context.
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# In tests (or local debugging), allow eager execution.
# Set CELERY_TASK_ALWAYS_EAGER=1 to run tasks inline.
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "0") == "1"
CELERY_TASK_EAGER_PROPAGATES = True

# ---------------------------------------------------------------------------
# Pipeline Orchestration Configuration
# ---------------------------------------------------------------------------
# Maximum number of retries per stage before marking the pipeline as failed.
ORCHESTRATION_MAX_RETRIES_PER_STAGE = int(
    os.environ.get("ORCHESTRATION_MAX_RETRIES_PER_STAGE", "3")
)

# Backoff factor for retry delays (exponential: factor^attempt seconds).
ORCHESTRATION_BACKOFF_FACTOR = float(os.environ.get("ORCHESTRATION_BACKOFF_FACTOR", "2.0"))

# Enable fallback when intelligence/AI stage fails.
# When True, pipeline continues with "AI unavailable" message instead of failing.
ORCHESTRATION_INTELLIGENCE_FALLBACK_ENABLED = (
    os.environ.get("ORCHESTRATION_INTELLIGENCE_FALLBACK_ENABLED", "1") == "1"
)

# Metrics backend for pipeline monitoring signals.
# Options: "logging" (default), "statsd"
ORCHESTRATION_METRICS_BACKEND = os.environ.get("ORCHESTRATION_METRICS_BACKEND", "logging")

# StatsD configuration (only used when ORCHESTRATION_METRICS_BACKEND=statsd)
STATSD_HOST = os.environ.get("STATSD_HOST", "localhost")
STATSD_PORT = int(os.environ.get("STATSD_PORT", "8125"))
STATSD_PREFIX = os.environ.get("STATSD_PREFIX", "pipeline")

# ---------------------------------------------------------------------------
# Checkers Configuration
# ---------------------------------------------------------------------------
# List of checker names to skip (disabled checkers).
# Can be set via environment variable as comma-separated list.
# Example: CHECKERS_SKIP=network,process
_skip_checkers = os.environ.get("CHECKERS_SKIP", "")
CHECKERS_SKIP: list[str] = [c.strip() for c in _skip_checkers.split(",") if c.strip()]
