"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from config.env import load_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load dotenv files early so os.environ is ready for settings below.
load_env(BASE_DIR)

# Add the 'apps' directory to sys.path
sys.path.insert(0, str(BASE_DIR / "apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Always require DJANGO_SECRET_KEY to be provided via environment/.env.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY environment variable is not set. " "Set it in your shell or .env file."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") in {"1", "true", "True", "yes", "on"}

_allowed_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS: list[str] = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "config.apps.MonitoringAdminConfig",
    "django_object_actions",
    "django_json_widget",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.alerts.apps.AlertsConfig",
    "apps.checkers.apps.CheckersConfig",
    "apps.intelligence.apps.IntelligenceConfig",
    "apps.notify.apps.NotifyConfig",
    "apps.orchestration.apps.OrchestrationConfig",
    "config.apps.ConfigAppConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.api_key_auth.APIKeyAuthMiddleware",
    "config.middleware.rate_limit.RateLimitMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_path_str = os.environ.get("DATABASE_PATH")
_db_path: Path
if _db_path_str:
    _p = Path(_db_path_str)
    _db_path = _p if _p.is_absolute() else BASE_DIR / _p
else:
    _db_path = BASE_DIR / "db.sqlite3"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Durable ingest / drain
# ---------------------------------------------------------------------------
# The pipeline runs broker-free: the webhook records a PENDING PipelineRun and
# `manage.py process_inbox` drains it (no Celery/Redis). doctor warns once the
# PENDING backlog exceeds this depth.
INBOX_DEPTH_WARN = int(os.environ.get("INBOX_DEPTH_WARN", "500"))

# ---------------------------------------------------------------------------
# Pipeline Orchestration Configuration
# ---------------------------------------------------------------------------
# Maximum number of retries per stage before marking the pipeline as failed.
ORCHESTRATION_MAX_RETRIES_PER_STAGE = int(
    os.environ.get("ORCHESTRATION_MAX_RETRIES_PER_STAGE", "3")
)

# Backoff factor for retry delays (exponential: factor^attempt seconds).
ORCHESTRATION_BACKOFF_FACTOR = float(os.environ.get("ORCHESTRATION_BACKOFF_FACTOR", "2.0"))

# Enable fallback when intelligence/AI stage fails.
# When True, pipeline continues with "AI unavailable" message instead of failing.
ORCHESTRATION_INTELLIGENCE_FALLBACK_ENABLED = (
    os.environ.get("ORCHESTRATION_INTELLIGENCE_FALLBACK_ENABLED", "1") == "1"
)

# Metrics backend for pipeline monitoring signals.
# Options: "logging" (default), "statsd"
ORCHESTRATION_METRICS_BACKEND = os.environ.get("ORCHESTRATION_METRICS_BACKEND", "logging")

# StatsD configuration (only used when ORCHESTRATION_METRICS_BACKEND=statsd)
STATSD_HOST = os.environ.get("STATSD_HOST", "localhost")
STATSD_PORT = int(os.environ.get("STATSD_PORT", "8125"))
STATSD_PREFIX = os.environ.get("STATSD_PREFIX", "pipeline")

# Cluster (multi-instance). An agent pushes to a hub authenticated by a single
# API key (Authorization: Bearer <HUB_API_KEY>); the hub accepts it via the API-key
# middleware. A node is a "hub" simply by holding an active APIKey with auth on —
# there is no separate CLUSTER_ENABLED flag.
HUB_URL = os.environ.get("HUB_URL", "")
INSTANCE_ID = os.environ.get("INSTANCE_ID", "")
HUB_API_KEY = os.environ.get("HUB_API_KEY", "")

# ---------------------------------------------------------------------------
# Django System Check Silencing
# ---------------------------------------------------------------------------
# Silence specific system check IDs so they don't appear during unrelated
# commands (e.g., migrate, runserver). The preflight command still shows all checks.
# Set via env var as comma-separated check IDs.
# Example: SILENCED_SYSTEM_CHECKS=checkers.W009,checkers.W010,checkers.I001
_silenced = os.environ.get("SILENCED_SYSTEM_CHECKS", "")
SILENCED_SYSTEM_CHECKS: list[str] = [c.strip() for c in _silenced.split(",") if c.strip()]

# ---------------------------------------------------------------------------
# API Key Authentication
# ---------------------------------------------------------------------------
API_KEY_AUTH_ENABLED = os.environ.get("API_KEY_AUTH_ENABLED", "1") == "1"

# ---------------------------------------------------------------------------
# Rate Limiting
# ---------------------------------------------------------------------------
RATE_LIMIT_ENABLED = os.environ.get("RATE_LIMIT_ENABLED", "0") == "1"

RATE_LIMITS = {
    "/alerts/": 120,
    "/orchestration/": 30,
    "/notify/": 30,
    "/intelligence/": 20,
}

# ---------------------------------------------------------------------------
# SSRF Protection
# ---------------------------------------------------------------------------
SSRF_ALLOWED_HOSTS: tuple[str, ...] = tuple(
    h.strip() for h in os.environ.get("SSRF_ALLOWED_HOSTS", "").split(",") if h.strip()
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

LOGS_DIR = Path(os.environ.get("LOGS_DIR", BASE_DIR / "logs"))
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "django.log",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "apps": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
