# Generated by Django 5.2.10 on 2026-01-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        db_index=True,
                        help_text="Correlation ID for tracing across stages.",
                        max_length=64,
                    ),
                ),
                (
                    "pipeline_run_id",
                    models.CharField(
                        db_index=True,
                        help_text="Pipeline run ID this analysis belongs to.",
                        max_length=64,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Intelligence provider used (e.g., 'local', 'openai').",
                        max_length=100,
                    ),
                ),
                (
                    "provider_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Provider configuration (redacted)."
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model name used for analysis.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Summary of input provided to the analysis.",
                    ),
                ),
                (
                    "checker_output_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to checker output used as input.",
                        max_length=255,
                    ),
                ),
                (
                    "recommendations_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of recommendations generated."
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True, default=list, help_text="List of recommendations."
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", help_text="Analysis summary."),
                ),
                (
                    "probable_cause",
                    models.TextField(
                        blank=True, default="", help_text="Probable cause identified."
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, help_text="Confidence score (0.0 to 1.0).", null=True
                    ),
                ),
                (
                    "prompt_tokens",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of prompt tokens used.", null=True
                    ),
                ),
                (
                    "completion_tokens",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of completion tokens used.", null=True
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total tokens used.", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "fallback_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a fallback was used instead of AI analysis.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.FloatField(default=0.0, help_text="Analysis duration in milliseconds."),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incident analyzed (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_runs",
                        to="alerts.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "status"], name="intelligenc_provide_1ca5fd_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="intelligenc_status_529f23_idx"
                    ),
                    models.Index(
                        fields=["incident", "created_at"], name="intelligenc_inciden_458479_idx"
                    ),
                ],
            },
        ),
    ]
