# Generated by Django 5.2.10 on 2026-02-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelligenceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this provider (e.g., 'production-claude').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("claude", "Claude (Anthropic)"),
                            ("gemini", "Gemini (Google)"),
                            ("copilot", "Copilot (GitHub)"),
                            ("grok", "Grok (xAI)"),
                            ("ollama", "Ollama (Local)"),
                            ("mistral", "Mistral"),
                        ],
                        db_index=True,
                        help_text="Provider driver type.",
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific config (api_key, model, max_tokens, etc.).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this provider is the active one. Only one can be active.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of this provider configuration.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
