# Generated by Django 5.2.10 on 2026-02-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_intelligenceprovider"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="intelligenceprovider",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_intelligence_provider",
            ),
        ),
    ]
