# Generated by Django 5.2.10 on 2026-01-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        db_index=True,
                        help_text="Correlation ID for tracing across all stages and logs.",
                        max_length=64,
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique ID for this specific pipeline run.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ingested", "Ingested"),
                            ("checked", "Checked"),
                            ("analyzed", "Analyzed"),
                            ("notified", "Notified"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ingest", "Ingest"),
                            ("check", "Check"),
                            ("analyze", "Analyze"),
                            ("notify", "Notify"),
                        ],
                        help_text="Current/last stage being executed.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        default="unknown",
                        help_text="Source system (e.g., 'grafana', 'alertmanager', 'custom').",
                        max_length=100,
                    ),
                ),
                (
                    "alert_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Alert fingerprint for deduplication.",
                        max_length=255,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        default="production",
                        help_text="Environment (e.g., 'production', 'staging').",
                        max_length=50,
                    ),
                ),
                (
                    "normalized_payload_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to normalized inbound payload (no raw secrets).",
                        max_length=255,
                    ),
                ),
                (
                    "checker_output_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to checker output.",
                        max_length=255,
                    ),
                ),
                (
                    "intelligence_output_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to intelligence output (prompt/response refs, redacted).",
                        max_length=255,
                    ),
                ),
                (
                    "notify_output_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to notification delivery results.",
                        max_length=255,
                    ),
                ),
                (
                    "intelligence_fallback_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the intelligence stage used a fallback (no AI analysis).",
                    ),
                ),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=1, help_text="Total number of attempts for this pipeline run."
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum retries allowed for this pipeline run."
                    ),
                ),
                ("last_error_type", models.CharField(blank=True, default="", max_length=255)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("last_error_retryable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When pipeline execution started.", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When pipeline execution completed (success or final failure).",
                        null=True,
                    ),
                ),
                (
                    "total_duration_ms",
                    models.FloatField(
                        default=0.0,
                        help_text="Total duration of pipeline execution in milliseconds.",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incident this pipeline run is associated with.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_runs",
                        to="alerts.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StageExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ingest", "Ingest"),
                            ("check", "Check"),
                            ("analyze", "Analyze"),
                            ("notify", "Notify"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attempt",
                    models.PositiveIntegerField(
                        default=1, help_text="Attempt number for this stage (1-based)."
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Key for idempotent stage execution.",
                        max_length=255,
                    ),
                ),
                (
                    "input_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to stage input data.",
                        max_length=255,
                    ),
                ),
                (
                    "output_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to stage output data.",
                        max_length=255,
                    ),
                ),
                (
                    "output_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of stage output (limited size, redacted).",
                    ),
                ),
                ("error_type", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_stack", models.TextField(blank=True, default="")),
                ("error_retryable", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.FloatField(
                        default=0.0, help_text="Stage execution duration in milliseconds."
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_executions",
                        to="orchestration.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["pipeline_run", "started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["trace_id", "run_id"], name="orchestrati_trace_i_cb4978_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["status", "created_at"], name="orchestrati_status_f31fac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["source", "alert_fingerprint"], name="orchestrati_source_c81a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stageexecution",
            index=models.Index(
                fields=["pipeline_run", "stage"], name="orchestrati_pipelin_a4ed28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stageexecution",
            index=models.Index(fields=["stage", "status"], name="orchestrati_stage_1b2407_idx"),
        ),
        migrations.AddIndex(
            model_name="stageexecution",
            index=models.Index(fields=["idempotency_key"], name="orchestrati_idempot_4e3b12_idx"),
        ),
        migrations.AddConstraint(
            model_name="stageexecution",
            constraint=models.UniqueConstraint(
                fields=("pipeline_run", "stage", "attempt"), name="unique_stage_attempt"
            ),
        ),
    ]
