# Generated by Django 5.2.10 on 2026-01-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this pipeline definition.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what this pipeline does.",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number, incremented on each update."
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Pipeline configuration schema (nodes, connections, defaults).",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary tags for filtering/categorization.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this pipeline can be executed.",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User or system that created this definition.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["name", "is_active"], name="orchestrati_name_cc0298_idx"),
                    models.Index(
                        fields=["is_active", "-updated_at"], name="orchestrati_is_acti_13bf32_idx"
                    ),
                ],
            },
        ),
    ]
