# Generated by Django 5.2.16 on 2026-07-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0003_remove_notification_log"),
        ("orchestration", "0002_add_pipeline_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinedefinition",
            name="channels",
            field=models.ManyToManyField(
                blank=True, related_name="pipelines", to="notify.notificationchannel"
            ),
        ),
        migrations.AddField(
            model_name="pipelinedefinition",
            name="match",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Routing conditions [{field, op, value}]; empty = catch-all.",
            ),
        ),
        migrations.AddField(
            model_name="pipelinedefinition",
            name="priority",
            field=models.IntegerField(
                db_index=True, default=100, help_text="Lower is evaluated first (first match wins)."
            ),
        ),
        migrations.AddField(
            model_name="pipelinedefinition",
            name="run_checkers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pipelinedefinition",
            name="run_intelligence",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pipelinedefinition",
            name="run_notify",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="pipelinedefinition",
            index=models.Index(
                fields=["is_active", "priority"], name="orchestrati_is_acti_93bb4e_idx"
            ),
        ),
    ]
