# Generated by Django 5.2.16 on 2026-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0003_pipelinedefinition_channels_pipelinedefinition_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="inbound_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw inbound payload captured at ingest so a drain can process this run.",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ingested", "Ingested"),
                    ("checked", "Checked"),
                    ("analyzed", "Analyzed"),
                    ("notified", "Notified"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
