# Generated by Django 5.2.16 on 2026-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0004_pipelinerun_inbound_payload_alter_pipelinerun_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelinedefinition",
            name="config",
        ),
        migrations.AlterField(
            model_name="pipelinedefinition",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Version number, bumped manually on significant edits."
            ),
        ),
    ]
