# Generated by Django 5.2.16 on 2026-08-09 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0008_node_is_self"),
        ("orchestration", "0005_remove_pipelinedefinition_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="Server this run concerns (agent node, or the hub self-node).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipeline_runs",
                to="alerts.node",
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="origin",
            field=models.CharField(
                choices=[
                    ("incoming_webhook", "Incoming webhook"),
                    ("checker_generated", "Checker generated"),
                    ("manual", "Manual / CLI"),
                ],
                db_index=True,
                default="incoming_webhook",
                help_text="How this run started (incoming push vs local checker vs manual).",
                max_length=20,
            ),
        ),
    ]
