# Generated by Django 5.2.16 on 2026-08-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0007_backfill_node_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxItem",
            fields=[],
            options={
                "verbose_name": "Inbox item",
                "verbose_name_plural": "Inbox",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orchestration.pipelinerun",),
        ),
    ]
