# Generated by Django 5.2.16 on 2026-08-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0009_remove_node_is_self"),
        ("orchestration", "0008_inboxitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinerun",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="Server this run concerns (the agent node resolved from the alert's instance_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipeline_runs",
                to="alerts.node",
            ),
        ),
    ]
