# Generated by Django 5.2.16 on 2026-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0012_seed_default_lanes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinedefinition",
            name="priority",
            field=models.IntegerField(
                db_index=True,
                default=100,
                help_text="Lower is evaluated first (first match wins). Convention: below 100 for system lanes that must pre-empt operator rules, 100 (the default) for your own lanes, 1000 for the catch-all that should only run when nothing else claimed the alert. Ties break on id, so avoid them.",
            ),
        ),
    ]
