# Generated by Django 5.2.16 on 2026-08-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0014_seed_hub_self_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinedefinition",
            name="stages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ordered downstream stages, e.g. ["check", "analyze", "notify"]. The entry stage is not listed: it has already run by the time this lane is resolved. INGEST is the entry stage for webhook traffic and CHECK for checker-generated runs (run_pipeline --checks-only); either way the lane is resolved from the alert that stage produced.',
            ),
        ),
    ]
