# Generated by Django 5.2.10 on 2026-01-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this channel (e.g., 'ops-slack', 'oncall-email').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "driver",
                    models.CharField(
                        db_index=True,
                        help_text="Driver type (e.g., 'slack', 'email', 'pagerduty', 'generic').",
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Driver-specific configuration (e.g., webhook URL, API key reference).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this channel is active and can receive notifications.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of this channel's purpose."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "driver",
                    models.CharField(
                        help_text="Driver used (stored separately in case channel is deleted).",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Notification title.", max_length=255)),
                ("message", models.TextField(help_text="Notification message body.")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("success", "Success"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External message ID returned by the driver (if available).",
                        max_length=255,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Error message if delivery failed."
                    ),
                ),
                (
                    "response_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional response metadata from the driver.",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tags associated with this notification.",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context data."
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Correlation ID for tracing.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the notification was actually sent.", null=True
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Channel used for this notification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notify.notificationchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"], name="notify_noti_status_3f3bd3_idx"
                    ),
                    models.Index(fields=["created_at"], name="notify_noti_created_3f9cba_idx"),
                    models.Index(fields=["driver", "status"], name="notify_noti_driver_43ba45_idx"),
                ],
            },
        ),
    ]
