# Generated by Django 5.2.10 on 2026-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="attempt",
            field=models.PositiveIntegerField(
                default=1, help_text="Attempt number for this notification (1-based)."
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Key for idempotent delivery (prevents duplicate sends).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="pipeline_run_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Associated pipeline run ID for orchestration tracking.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="queued_at",
            field=models.DateTimeField(
                blank=True, help_text="When the notification was queued for delivery.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["pipeline_run_id"], name="notify_noti_pipelin_f0e2ff_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["idempotency_key"], name="notify_noti_idempot_91f37c_idx"),
        ),
    ]
