# Generated by Django 5.2.10 on 2026-01-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0002_notificationlog_attempt_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationLog",
        ),
    ]
